# Generated by Django 6.0.3 on 2026-04-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contactmessage_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='BogoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='offers/products/')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Buy 1 Get 1 Product',
                'verbose_name_plural': 'Buy 1 Get 1 Products',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExclusiveOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Exclusive Kit: The Midnight Repair Set', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='offers/exclusive/')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.IntegerField(default=35)),
                ('button_text', models.CharField(default='Claim This Offer', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Join The Inner Circle', max_length=200)),
                ('description', models.CharField(default='Sign up to receive early access to new launches, exclusive offers and skincare tips.', max_length=300)),
                ('button_text', models.CharField(default='Register', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='offers/newsletter/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BIG SALE!', max_length=200)),
                ('subtitle', models.CharField(default='UP TO 50% OFF', max_length=200)),
                ('offer_text', models.CharField(default='LIMITED TIME OFFER', max_length=200)),
                ('heading', models.CharField(default='Unbeatable Deals on Top Brands!', max_length=200)),
                ('sub_heading', models.CharField(default='Shop now and save big on your', max_length=300)),
                ('banner_image', models.ImageField(upload_to='offers/banners/')),
                ('discount_1', models.CharField(default='40%', max_length=10)),
                ('discount_2', models.CharField(default='30%', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Main Offer Banner',
                'verbose_name_plural': 'Main Offer Banner',
            },
        ),
    ]
