# Generated by Django 6.0.3 on 2026-04-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bogoproduct_exclusiveoffer_newslettersection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='The Art of Radiant Skin', max_length=200)),
                ('hero_subtitle', models.TextField(default='The legacy of timeless beauty and scientific precision, crafted for the modern connoisseur')),
                ('hero_bg_image', models.ImageField(upload_to='about/hero/')),
                ('story_title', models.CharField(default='Our story', max_length=200)),
                ('story_content', models.TextField()),
                ('story_image', models.ImageField(upload_to='about/story/')),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='CommitmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Unwavering Commitment', max_length=200)),
                ('content', models.TextField()),
                ('button_text', models.CharField(default='View sustainability Report', max_length=100)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about/values/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FounderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Meet the Founder', max_length=200)),
                ('founder_name', models.CharField(default='Elena', max_length=100)),
                ('founder_image', models.ImageField(upload_to='about/founder/')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
