# Generated by Django 6.0.3 on 2026-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_loginrecord_product_brand_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corevalue',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='story_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commitmentsection',
            name='button_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commitmentsection',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exclusiveoffer',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foundersection',
            name='founder_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foundersection',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newslettersection',
            name='description',
            field=models.CharField(default='Exclusive offers and tips', max_length=300),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='sub_heading',
            field=models.CharField(default='Shop now and save big', max_length=300),
        ),
    ]
