# Generated by Django 6.0.3 on 2026-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_corevalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(default='Cream Luxe (Satin Glow)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.CharField(default='3.5g', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(default='Suitable for all', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(default='Luxury. Comfort. Timeless Color.', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
